// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainSchedule.Data;

#nullable disable

namespace TrainSchedule.Migrations
{
    [DbContext(typeof(TrainScheduleDbContext))]
    partial class TrainScheduleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrainSchedule.Models.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Train", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalCity = "Одеса",
                            AvailableSeats = 20,
                            DepartureCity = "Харків",
                            TrainNumber = "DE1"
                        },
                        new
                        {
                            Id = 2,
                            ArrivalCity = "Одеса",
                            AvailableSeats = 48,
                            DepartureCity = "Київ",
                            TrainNumber = "WE5"
                        },
                        new
                        {
                            Id = 3,
                            ArrivalCity = "Рубіжне",
                            AvailableSeats = 35,
                            DepartureCity = "Харків",
                            TrainNumber = "R45"
                        },
                        new
                        {
                            Id = 4,
                            ArrivalCity = "Рубіжне",
                            AvailableSeats = 5,
                            DepartureCity = "Київ",
                            TrainNumber = "D4"
                        },
                        new
                        {
                            Id = 5,
                            ArrivalCity = "Суми",
                            AvailableSeats = 48,
                            DepartureCity = "Київ",
                            TrainNumber = "WE5"
                        },
                        new
                        {
                            Id = 6,
                            ArrivalCity = "Київ",
                            AvailableSeats = 48,
                            DepartureCity = "Лисичанськ",
                            TrainNumber = "WE5"
                        },
                        new
                        {
                            Id = 7,
                            ArrivalCity = "Київ",
                            AvailableSeats = 30,
                            DepartureCity = "Львів",
                            TrainNumber = "IC123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
